### ISSUE TITLE
update-golang

### ISSUE THREAD

**Issue by udhos** [DieTime/go-up#1]
Hi!

Nice project!

You might want to have a look at this one as well:

https://github.com/udhos/update-golang

Best regards

**Comment by DieTime** [comment]
@udhos
Hello, thanks for the link. I have read this project, I liked it, but it does not fit my needs for the following reasons.

1. I install Go at the path `~/.local/opt/go` and set the `$GOPATH` as `~/.local/opt/go/gopath`
2. When I run the command: `env DESTINATION=~/.local/opt GOPATH=~/.local/opt/go/gopath ./update-golang.sh`.\
    I get an error: `./update-golang.sh: line 532: cd: ~/.local/opt: No such file or directory`
3. The `README.md` also says to use `sudo` for installation by default. Although if the destination directory belongs to the current user, this is not necessary.

So I had to write my own script with these points in mind.
Best regards.

**Comment by udhos** [comment]
Hi!

I understand you hit that issue because the destination dir didnt't exist!

If you create it beforehand, would it work for you?

Like this

```
mkdir ~/.local/opt
DESTINATION=~/.local/opt GOPATH=~/.local/opt/go/gopath ./update-golang.sh
```

Just curious if it would suit your intended layout!
